name:                matrix-lens
version:             0.1.0.0
github:              "interosinc/matrix-lens"
license:             BSD3
author:              "Interos, Inc."
maintainer:          "jevans@interos.ai"
copyright:           "2020 Interos, Inc."

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Optics for the "matrix" package
category:            Math

description:         See README at <https://github.com/interosinc/matrix-lens#readme>

flags:
  developer:
    description: Developer mode -- stricter handling of compiler warnings.
    manual: True
    default: False

when:
  - condition: flag(developer)
    then:
      ghc-options:
      - -Weverything
      - -Werror
      - -Wno-all-missed-specialisations
      - -Wno-missed-specialisations
      - -Wno-missing-deriving-strategies
      - -Wno-missing-exported-signatures
      - -Wno-missing-import-lists
      - -Wno-missing-local-signatures
      - -Wno-monomorphism-restriction
      - -Wno-safe
      - -Wno-unsafe
    else:
      ghc-options:
      - -Weverything
      - -Wno-all-missed-specialisations
      - -Wno-missed-specialisations
      - -Wno-missing-deriving-strategies
      - -Wno-missing-exported-signatures
      - -Wno-missing-import-lists
      - -Wno-missing-local-signatures
      - -Wno-monomorphism-restriction
      - -Wno-safe
      - -Wno-unsafe

dependencies:
- base    >= 4.7    && < 5
- lens    >= 4.19.2 && < 4.20
- vector  >= 0.12.1 && < 0.13
- matrix  >= 0.3.6  && < 0.4

library:
  source-dirs: src

tests:
  matrix-lens-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog
    - matrix-lens
    - tasty
    - tasty-discover
    - tasty-hedgehog
    - tasty-hspec
